### ISSUE TITLE
Can not load texture

### ISSUE THREAD

**Issue by Matze997** [mario-deluna/php-glfw#12]
Hey,
I tried following your example of [loading 2d textures](https://phpgl.net/API/Texture/Texture2D.html), but when I tried it myself the class Texture2D didn´t exist. 
I´ve checked if I installed everything correctly and I´m pretty sure that I havn´t missed anything.
You´re example window works

PHP Version: 8.1
Release used: https://github.com/mario-deluna/php-glfw/releases/download/v2.1.2/glfw_php8.1_ts_x64.zip

I couldn´t find anything in the stubs, too

**Comment by Matze997** [comment]
Sry

PHP Version: 8.2.5
Release: https://github.com/mario-deluna/php-glfw/releases/download/v2.1.2/glfw_php8.2_ts_x64.zip

**Comment by mario-deluna** [comment]
Hey, stupid question but are you using the proper namespace?

`GL\Texture\Texture2D::fromDisk(__DIR__ . '/picture.png');`

The docs don't make it perfectly clear, that the class is in a namespace.

**Comment by Matze997** [comment]
Thank you
Got it to work

I really like your project btw haha
