### ISSUE TITLE
maximize window problem

### ISSUE THREAD

**Issue by odarcan** [mario-deluna/php-glfw#20]
Hi,
edit: I made it work

By the way I some guy made my game into a flatpak package, my php-glfw game now works on most linux distros according to them!

the custom flatpak repo is on my pc, I can send it to you if you want, 
building instructions are on my github repository I got it from him.

**Comment by mario-deluna** [comment]
Awesome, for reference I think this is the repo you are referencing? 
https://github.com/Jookia/flatpak-php-glfw-test

**Comment by odarcan** [comment]
yes that's the one, it is very easy to use.

**Comment by odarcan** [comment]
But you have to put a repo online somewhere I think, maybe it can draw from github directly somehow.
