### ISSUE TITLE
extra support

### ISSUE THREAD

**Issue by odarcan** [mario-deluna/php-glfw#21]
Hi Mario do you have a buy me coffee link for extra support ?

**Comment by mario-deluna** [comment]
Any support is highly appreciated! :) If you wish to buy me a coffee you can sponsor me on GitHub. 

Current things in the works
* The bundler, MacOS is working already but still needs quite a bit of work as-well as obviously support for other platforms. https://github.com/phpgl/visu-bundler
* An additional HTML5 canvas inspired vector graphics API, great for testing things out and UI drawing or simple graphics. https://github.com/mario-deluna/php-glfw/pull/22
