### ISSUE TITLE
requirements for the glfwInit() command

### ISSUE THREAD

**Issue by Poleg44** [mario-deluna/php-glfw#24]
I try to execute 01_triangle.php example at Raspberry 3B+, Bookworm version.
I get exception "GLFW could not be initialized!".

Can i init from CLI mode?

my php version:
pi@raspberrypi:~/php-glfw/examples $ php -v
PHP 8.3.0 (cli) (built: Nov 25 2023 14:38:03) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.0, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.0, Copyright (c), by Zend Technologies
GLFW installed:
pi@raspberrypi:~/php-glfw/examples $ php -m
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
glfw
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
random
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

My finish task is real image render as i create GD image and transfer it to client.
//image generate
......
header ("Content-type: image/png");
imagepng($image);

**Comment by mario-deluna** [comment]
Hey @Poleg44 

Im guessing you are trying to run the code in a pure CLI environment, so without an xserver or GUI?

In that case you will need to create a virtual screen buffer on which you can open a context.

We do the same thing to run the unitests inside of the GitHub Actions.

```
xvfb-run --auto-servernum php ./path/to/your/file.php
```

Note, that you probably want to run glfw in headless mode: https://www.glfw.org/docs/latest/context.html#context_offscreen

**Comment by mario-deluna** [comment]
Also you can use [`glReadPixels`](https://phpgl.net/API/OpenGL/glReadPixels.html) to retrieve the bitmap, we currently provide no helpers tho to convert that bitmap to a jpg or png.

**Comment by Poleg44** [comment]
Thank you!
After xvfb-run --auto-servernum script run without error and exception.

1. I take 01_triangle.php example as basic.
2. Cancel loop
3. And want to read buffer via
glReadPixels(0, 0, 800, 800, int $format, int $type, \GL\Buffer\BufferInterface $pixels);
But i dont have info how use this command.
what is $format, $type, $pixel?
Is there example with this function?

**Comment by mario-deluna** [comment]
Here is a small example how to write the current buffer to a `.tga` image, this is slow and not optimised tho.

```php
// read the pixel data
$pixelBuffer = new \GL\Buffer\UByteBuffer();
glReadPixels(0, 0, 800, 800, GL_RGB, GL_UNSIGNED_BYTE, $pixelBuffer);

// write to a tga file manually
$tgaFile = fopen('triangle.tga', 'wb');
fwrite($tgaFile, pack('c*', 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0));
fwrite($tgaFile, pack('v*', 800, 800, 24));
foreach ($pixelBuffer as $byte) {
    fwrite($tgaFile, pack('C', $byte));
}
```

**Comment by Poleg44** [comment]
thank you! I got file with picture.
