### ISSUE TITLE
Problem with initializing VGContext with ANTIALIAS in Coca

### ISSUE THREAD

**Issue by mtk3d** [mario-deluna/php-glfw#26]
Hi,

I have an issue with running example number 11, with vector graphics. I had tested it on multiple configurations (described below), and I found out that code is failing on `VGContext` class instantiating (examples/11_vector_graphics.php:17).

**Error output:**

```
php examples/11_vector_graphics.php
3.3.8 Cocoa NSGL EGL OSMesa dynamic
fish: Job 1, 'php examples/11_vector_graphics…' terminated by signal SIGSEGV (Address boundary error)
```

**Environment:**

- Hardware: MacBook Pro Intel arch
- OS: Sonoma 14.2 (23C64)
- PHP versions: 8.3.0 / 8.3.1 / 8.2.14 - installed from brew
- Cocoa: 3.3.8
- Installation: by building from cloned source / by simple installer script

**Comment by mtk3d** [comment]
Ok, I found a solution. It's failing if the `ANTIALIAS` flag is used. I removed this parameter and now it works.
Maybe this flag could be removed to make it work in more configurations?

**Comment by mario-deluna** [comment]
Hey @mtk3d, Thank you very much for the report. Im happy to hear you got it running. 

Im running an older version of MacOS personally, I don't necessarly think this is the issue but it is the first thing jumping into my eye. 

I would really like to resolve this issue, can you by any chance provide a stack trace? 

On MacOS `lldb` should be preinstalled:

```
lldb php examples/11_vector_graphics.php
```

* Then type `run`.
* After it crashes type `bt`

That would really help :)

**Comment by odarcan** [comment]
@mario-deluna 
I have an idea to make php available for coding apps on ios, interested?

**Comment by mario-deluna** [comment]
Hey @odarcan, the main task would be to create bindings for UIKit, or at least the I/O parts of it. I'm sure it's possible, but it would definitely be a separate repository. Quite a bit of this codebase could probably be reused.

Now, if you want to discuss this further, I ask you to open a separate issue ;)

**Comment by mtk3d** [comment]
@mario-deluna Hey, sure there is the stack trace file 😄 
[stacktrace.txt](https://github.com/mario-deluna/php-glfw/files/13928034/stacktrace.txt)

**Comment by mario-deluna** [comment]
This one took me far longer to fix than anticipated. I had to borrow an Intel Mac 😅.

Turns out I made a dumb mistake where I was writing a long into an int, and somehow this only caused an issue on Intel Macs.

https://github.com/mario-deluna/php-glfw/commit/56f6e1966d7d77e0bebb5fdecd0c6eff75c8e9b8

Fixed now.

Thank you very much for the report and stack trace.

**Comment by mtk3d** [comment]
Great, thanks!
