### ISSUE TITLE
email for communication

### ISSUE THREAD

**Issue by odarcan** [mario-deluna/php-glfw#27]
@mario-deluna Hi can I have your email address pls.

**Comment by mario-deluna** [comment]
I wrote you an email via your GitHub handle 70048810+odarcan@users.noreply.github.com because I would rather not post my email address here publicly ;)

**Comment by odarcan** [comment]
No way i didnt know you could do thisI am in the process of thinking out a way of bringing php programming to making apps on iosA frameworkAnd you are a php enthusiast so i want your opinionsSent from my iPhoneOn 12 Jan 2024, at 03:01, Mario Döring ***@***.***> wrote:﻿
Closed #27 as completed.
