### ISSUE TITLE
installation problem "implicit declaration of function ‘ZEND_ARG_OBJ_TYPE_MASK’"

### ISSUE THREAD

**Issue by odarcan** [mario-deluna/php-glfw#3]
Hello I ran into a problem when installing

output is here: https://termbin.com/jwsbd

**Comment by odarcan** [comment]
for more userfriendly instructions I suggest you add these 

sudo apt install phpn.n-dev

sudo apt install libglfw3-dev

**Comment by mario-deluna** [comment]
It looks like your trying to install the extension with a PHP version < 8.0.

Have you been able to resolve the issue?

**Comment by odarcan** [comment]
I have php 7.4

**Comment by mario-deluna** [comment]
I see, I've added a Note to the installation section in the README just now. 

Sorry it was no were stated before, the extension has a minimum platform requirement of **PHP8.0**.

**Comment by odarcan** [comment]
I upgraded to php 8
it works now!
this is amazing

I tried some examples they work but for some it says zip extension missing

**Comment by odarcan** [comment]
and for 07 example it says simplexml_load_file undefined function
and for test.php it says glShaderSource() expects 2 arguments, 3 given

**Comment by odarcan** [comment]
Can this be packaged in a way for easy distribution ?

I use linux I think this has great potential, multiplayer sound etc etc

**Comment by mario-deluna** [comment]
> Can this be packaged in a way for easy distribution?

Technically yes, it should be possible to bundle the PHP runtime with the compiled extension together into a single self contained application installation. You could even compile PHP from source with php-glfw enabled as a standard extension. And then distributing the PHP-Runtime itself with your application code. 

But this is something still on my todo list to make it easy accessible or to write some guide on how to. On windows this is rather simple as you can just download the precompiled PHP, download the php-glfw.dll and create a shortcut running `path/to/php.exe path/to/some.php`.

**Comment by odarcan** [comment]
Do you think this can run on ipad, iphone, android ?
