### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by Ziggizag** [mario-deluna/php-glfw#30]
ziggi@WAW01MCL-113866:~/php-glfw$ sudo make install
/bin/bash /home/ziggi/php-glfw/libtool --mode=compile cc -Wno-unicode -DNVG_NO_STB=1 -D_GLFW_X11 -Wall -I. -I/home/ziggi/php-glfw -DPHP_ATOM_INC -I/home/ziggi/php-glfw/include -I/home/ziggi/php-glfw/main -I/home/ziggi/php-glfw -I/usr/include/php/20190902 -I/usr/include/php/20190902/main -I/usr/include/php/20190902/TSRM -I/usr/include/php/20190902/Zend -I/usr/include/php/20190902/ext -I/usr/include/php/20190902/ext/date/lib -I/home/ziggi/php-glfw -I/home/ziggi/php-glfw/vendor/glad/include -I/home/ziggi/php-glfw/vendor/cvector -I/home/ziggi/php-glfw/vendor/stb -I/home/ziggi/php-glfw/vendor/fastobj -I/home/ziggi/php-glfw/vendor/nanovg/src -I/usr/local/include  -DHAVE_CONFIG_H  -g -O2   -c /home/ziggi/php-glfw/phpglfw.c -o phpglfw.lo
libtool: compile:  cc -Wno-unicode -DNVG_NO_STB=1 -D_GLFW_X11 -Wall -I. -I/home/ziggi/php-glfw -DPHP_ATOM_INC -I/home/ziggi/php-glfw/include -I/home/ziggi/php-glfw/main -I/home/ziggi/php-glfw -I/usr/include/php/20190902 -I/usr/include/php/20190902/main -I/usr/include/php/20190902/TSRM -I/usr/include/php/20190902/Zend -I/usr/include/php/20190902/ext -I/usr/include/php/20190902/ext/date/lib -I/home/ziggi/php-glfw -I/home/ziggi/php-glfw/vendor/glad/include -I/home/ziggi/php-glfw/vendor/cvector -I/home/ziggi/php-glfw/vendor/stb -I/home/ziggi/php-glfw/vendor/fastobj -I/home/ziggi/php-glfw/vendor/nanovg/src -I/usr/local/include -DHAVE_CONFIG_H -g -O2 -c /home/ziggi/php-glfw/phpglfw.c  -fPIC -DPIC -o .libs/phpglfw.o
In file included from /home/ziggi/php-glfw/phpglfw.c:33:
/home/ziggi/php-glfw/phpglfw_arginfo.h:44:9: warning: implicit declaration of function ‘ZEND_ARG_OBJ_TYPE_MASK’; did you mean ‘ZEND_VM_EXT_TYPE_MASK’? [-Wimplicit-function-declaration]
   44 |         ZEND_ARG_OBJ_TYPE_MASK(0, params, GL\\Buffer\\FloatBuffer, MAY_BE_ARRAY, NULL)
      |         ^~~~~~~~~~~~~~~~~~~~~~
      |         ZEND_VM_EXT_TYPE_MASK
/home/ziggi/php-glfw/phpglfw_arginfo.h:44:35: error: ‘params’ undeclared here (not in a function)
   44 |         ZEND_ARG_OBJ_TYPE_MASK(0, params, GL\\Buffer\\FloatBuffer, MAY_BE_ARRAY, NULL)
      |                                   ^~~~~~
/home/ziggi/php-glfw/phpglfw_arginfo.h:44:45: error: stray ‘\’ in program
   44 |         ZEND_ARG_OBJ_TYPE_MASK(0, params, GL\\Buffer\\FloatBuffer, MAY_BE_ARRAY, NULL)
      |                                             ^
/home/ziggi/php-glfw/phpglfw_arginfo.h:44:46: error: stray ‘\’ in program
   44 |         ZEND_ARG_OBJ_TYPE_MASK(0, params, GL\\Buffer\\FloatBuffer, MAY_BE_ARRAY, NULL)
      |                                              ^

/many lines like above/
                                                                   ^
cc1: note: unrecognized command-line option ‘-Wno-unicode’ may have been intended to silence earlier diagnostics
make: *** [Makefile:192: phpglfw.lo] Error 1

**Comment by mario-deluna** [comment]
Hey @Ziggizag. 

Thanks for the report, this looks like you are using a PHP version < 8.0.

Can you verify you are using PHP version >= 8.0?

Regards Mario

**Comment by Ziggizag** [comment]
Indeed - for compatibility with some important legacy app I am still on PHP 7.4.33.

Sorry for bothering you, but I simply did not notice PHP-Supprt banner.
Thank you for a prompt feedback - anyway - simple PHP-version check would be helpful ;)

Rgs!

**Comment by mario-deluna** [comment]
> simple PHP-version check would be helpful ;)

Fair enough, should definitely be added.

We unfortunately have no precompiled binaries for linux at the moment.
