### ISSUE TITLE
Unable to load dynamic library 'glfw.so'

### ISSUE THREAD

**Issue by zimbar** [mario-deluna/php-glfw#36]
Hy

I have fedora 40 with php 8.3.13, i installed php-glfw without error, but when i try the exemple "php 03_textured_cube.php" i have this error :

=> Unable to load dynamic library 'glfw.so' (tried: /usr/lib64/php/modules/glfw.so (libglfw.so.3: cannot open shared object file: No such file or directory), /usr/lib64/php/modules/glfw.so.so (/usr/lib64/php/modules/glfw.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

I also added extension="glfw.so" in my php.ini and glfw.so exist in /usr/lib64/php/modules.

Thanks

**Comment by mario-deluna** [comment]
I'm not sure with the information at hand, but if I had to guess, it sounds a little like the `glfw.so` file is linked to the shared GLFW library, which it cannot find at startup.

Could you double-check that you have `glfw` and its dependencies installed?

```
sudo dnf install glfw-devel wayland-devel libxkbcommon-devel libXcursor-devel libXi-devel libXinerama-devel libXrandr-devel
```

Alternatively, I would try to install php-glfw and statically link glfw into it.

**Comment by zimbar** [comment]
Hy,

Thanks, it's working now.
