### ISSUE TITLE
Hello again

### ISSUE THREAD

**Issue by odarcan** [mario-deluna/php-glfw#4]
The examples and instructions are very neat I hope there can be more variety added to them 
I havent used opengl before but I know php well, I am sort of bruteforcing solutions and learning at the same time

I still havent figured out how to add objects while in the loop

and without going into shaders and complicated stuff it would be great if I could just add flat surface textures to objects and a simple point lamp in the air

Can this be ported to ipad iphone and android you think?

Where would people that want to talk about this hang out ? thanks

**Comment by odarcan** [comment]
If this can access gps gyroscope compass of a ipad iphone android device youd be able to do tons of stuff and applications entirely in php.

**Comment by mario-deluna** [comment]
Hey there

> I still havent figured out how to add objects while in the loop
> 
> and without going into shaders and complicated stuff it would be great if I could just add flat surface textures to objects and a simple point lamp in the air

I've been working on a PHP library on top of PHP-GLFW with the target of providing some scafolding and opinionated abstractions specifically for realtime applications. A framework for GL apps if you will in PHP. 

https://github.com/phpgl/visu

Im right now implementing a frame graph / render graph system there, and directly following that a simple ECS. 

The library is really far from finished, but some of the components there might provide a useful reference. 

In the ideal world VISU should provide a predefined rendering pipeline where you literally can just do something like this:

```php
$world = new WorldScene;
$world->addSystem(new RenderingSystem());
$world->addSystem(new CameraSystem());

$lamp = $world->entities->create();
$world->entities->component($lamp, new LampComponent($brightness));
$world->entities->component($lamp, new Transform(0, 20, 0));

 ...

$visu = new VISU();
$vsu->runScene($world);
```

This code is purely made up, it's just there to give an idea of what VISU is trying to achieve. 

The good thing about OpenGL is you can utilise tutorials in C++, sure the syntax is different but the overall concepts are identical. I highly recommend: https://learnopengl.com/Lighting/Light-casters 

This in combination with the examples provided here should get you quite far. And if questions or difficulties arise feel free to ask! 

---

> Can this be ported to ipad iphone and android you think?

Technically I would say yes, but I don't think it's something you could get working in a weekend. 

---

> Where would people that want to talk about this hang out ? thanks

I've enabled GitHub discussions for this project:
https://github.com/mario-deluna/php-glfw/discussions

As there is not really a community around this yet, the php subreddit is for sure also a good place :)
